
mack = User.find_by(email: "mackenzie.moore@gpmail.org")
Contact.create({:name=>"Alisa", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>11, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Angela", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>11, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Eun Ah Park", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>11, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Yuqi", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>8, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Harriet", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>21, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Lina", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>13, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Shiho", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>3, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Manami", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>3, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Angie", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>15, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Hsinhang", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Linya", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>13, :school_status=>"Visiting scholar", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Terry", :gender=>"male", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>"Visiting scholar", :major=>"Entomology", :admin_level=>mack})
Contact.create({:name=>"Jian Bo", :gender=>"male", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>"Visiting scholar", :major=>"Geology", :admin_level=>mack})
Contact.create({:name=>"Monica", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>13, :school_status=>"housewife", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Valeria Eim Izardo", :gender=>"female", :email=>"valeria.eim@uib.es", :phone_number=>"34660942527", :user_id=>22, :school_status=>"Visiting Scholar ", :major=>"BAE (bainer hall)", :admin_level=>mack})
Contact.create({:name=>"Satoski Haginyoa", :gender=>"female", :email=>"shaginoya@ucdavis.edu", :phone_number=>"530 601 0520", :user_id=>22, :school_status=>"Visiting Scholar ", :major=>"VMTH", :admin_level=>mack})
Contact.create({:name=>"Clarena", :gender=>"female", :email=>"clare.a18@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Daniel", :gender=>"male", :email=>"quicetor@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Ayana Baba", :gender=>"female", :email=>"ayababa@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"Exchange Student", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Yiwen", :gender=>"male", :email=>"yiwen.hu@tum.de", :phone_number=>"530-204-8750", :user_id=>22, :school_status=>"visiting scholar", :major=>"bae", :admin_level=>mack})
Contact.create({:name=>"Ratta", :gender=>"male", :email=>"raththar@hotmail.com", :phone_number=>"530-220-5071", :user_id=>22, :school_status=>"visiting scholar", :major=>"bae", :admin_level=>mack})
Contact.create({:name=>"Doris", :gender=>"female", :email=>"jxdong@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Eiri Nozaki", :gender=>"female", :email=>"enozaki@ucdavis.edu", :phone_number=>"+1(214)940-4080", :user_id=>2, :school_status=>"Undergraduate Student", :major=>"Politics(in japanese university)", :admin_level=>mack})
Contact.create({:name=>"Alec", :gender=>"male", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Sophie Seohui Cho", :gender=>"female", :email=>"Sfycho@ucdavis.edu", :phone_number=>nil, :user_id=>15, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Jonas", :gender=>"male", :email=>"Jelanglois@ucdavis.edu", :phone_number=>"5307609262", :user_id=>22, :school_status=>"Undergraduate Student", :major=>"Mae", :admin_level=>mack})
Contact.create({:name=>"Fu (missing first name)", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>19, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Jia jia", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>19, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Mikiko Tao", :gender=>"female", :email=>"miktao@ucdavis.edu", :phone_number=>"530 564 2885", :user_id=>2, :school_status=>"Exchange Student", :major=>"Economics", :admin_level=>mack})
Contact.create({:name=>"Rabigh", :gender=>"male", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Aina", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>3, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Lin", :gender=>"female", :email=>nil, :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Toshi", :gender=>"male", :email=>" ", :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Eleanor (Xueyong) Zhang", :gender=>"female", :email=>"hqezhang@ucdavis.edu", :phone_number=>"5307609522", :user_id=>5, :school_status=>"undergrad", :major=>"psychology", :admin_level=>mack})
Contact.create({:name=>"Tricia Ye", :gender=>"female ", :email=>"tcye@ucdavis.edu", :phone_number=>"8324976714", :user_id=>21, :school_status=>"undergrad", :major=>"BME", :admin_level=>mack})
Contact.create({:name=>"Yang Mu", :gender=>"male", :email=>"mymu@ucdavis.edu", :phone_number=>"5302048703", :user_id=>16, :school_status=>"exchange student", :major=>"Micro Bio", :admin_level=>mack})
Contact.create({:name=>"Lily", :gender=>"female ", :email=>"meiyao@ucdavis.edu", :phone_number=>nil, :user_id=>5, :school_status=>"undergrad", :major=>"Physics", :admin_level=>mack})
Contact.create({:name=>"yiran ma ", :gender=>"female ", :email=>"yrma@ucdavis.edu", :phone_number=>"5307616948", :user_id=>5, :school_status=>"undergrad", :major=>"cbs", :admin_level=>mack})
Contact.create({:name=>"Yvette", :gender=>"female ", :email=>"sunyvetteiii@gmail.com", :phone_number=>"5302203127", :user_id=>19, :school_status=>"visiting scholar ", :major=>"Textile", :admin_level=>mack})
Contact.create({:name=>"Zhemin huang ", :gender=>"female ", :email=>"zmhuang@ucdavis.edu", :phone_number=>"5309793389", :user_id=>21, :school_status=>"undergrad", :major=>"Sociology ", :admin_level=>mack})
Contact.create({:name=>"Jack Yang", :gender=>"male", :email=>"ycy20131007@163.com", :phone_number=>nil, :user_id=>22, :school_status=>"undergrad", :major=>"theatre", :admin_level=>mack})
Contact.create({:name=>"Leo", :gender=>"male", :email=>"m0931757580@gmail.com", :phone_number=>"9199497865", :user_id=>22, :school_status=>"交换生", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Bernice", :gender=>"female ", :email=>"yuyu_0516@yahoo.com", :phone_number=>nil, :user_id=>19, :school_status=>"交换生", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Mike Li", :gender=>"male", :email=>"zijli@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"yunfei yang (Doris)", :gender=>"female ", :email=>"vlsyang@ucdavis.edu", :phone_number=>nil, :user_id=>8, :school_status=>"undergrad", :major=>"nutrition", :admin_level=>mack})
Contact.create({:name=>"Celestia (not new just FYI)", :gender=>"female ", :email=>"junfang@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"undergrad", :major=>"Npb", :admin_level=>mack})
Contact.create({:name=>"Lei qian", :gender=>"female ", :email=>"leiqian@ucdavis.com", :phone_number=>nil, :user_id=>5, :school_status=>"Other", :major=>"English Program", :admin_level=>mack})
Contact.create({:name=>"Yuhan fu", :gender=>"female ", :email=>"yhfu@ucdavis.edu", :phone_number=>"5302205029", :user_id=>21, :school_status=>"undergrad", :major=>"Biology", :admin_level=>mack})
Contact.create({:name=>"Crystal", :gender=>"female ", :email=>"jyzzhang@ucdavis.edu", :phone_number=>nil, :user_id=>5, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Shujuan Chen (Amber)", :gender=>"female ", :email=>"csjchen@ucdavis.edu", :phone_number=>nil, :user_id=>14, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Jiawei Jiang (Vanilla)", :gender=>"female ", :email=>"dzjiang@ucdavis.edu", :phone_number=>"5303026013", :user_id=>8, :school_status=>"undergrad", :major=>"Psychology", :admin_level=>mack})
Contact.create({:name=>"jing", :gender=>"female ", :email=>"zhangxiaolai 103@gmail.com", :phone_number=>nil, :user_id=>13, :school_status=>"Other", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"David", :gender=>"male", :email=>"Tsaiwr@gmail.com", :phone_number=>nil, :user_id=>16, :school_status=>"Other", :major=>"Computer", :admin_level=>mack})
Contact.create({:name=>"Yifei peng", :gender=>"male", :email=>"NIUbi530@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>"undergrad", :major=>"Mathmatics", :admin_level=>mack})
Contact.create({:name=>"xiang", :gender=>"male", :email=>"xzh@ucdavis.edu", :phone_number=>"5397461950", :user_id=>16, :school_status=>"undergrad", :major=>"economics", :admin_level=>mack})
Contact.create({:name=>"Yijing Wang", :gender=>"female ", :email=>"whswang@ucdavis.edu", :phone_number=>"5306319869", :user_id=>5, :school_status=>"undergrad", :major=>"economics", :admin_level=>mack})
Contact.create({:name=>"Xinhang Yang", :gender=>"male", :email=>"xinhang@ucdavis.edu", :phone_number=>"5307609306", :user_id=>22, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Jingxuan Wu (Theresa)", :gender=>"female ", :email=>"teswu@ucdavis.edu", :phone_number=>"5305649189", :user_id=>14, :school_status=>"undergrad", :major=>"Civil Engineering ", :admin_level=>mack})
Contact.create({:name=>"Hanshi Sha", :gender=>"female ", :email=>"shssha@ucdavis.edu", :phone_number=>"2624083688", :user_id=>8, :school_status=>"undergrad", :major=>"communication", :admin_level=>mack})
Contact.create({:name=>"Stephanie Louie", :gender=>"female ", :email=>"ycslouie@ucdavis.edu", :phone_number=>"6282196775", :user_id=>14, :school_status=>"undergrad", :major=>"communication", :admin_level=>mack})
Contact.create({:name=>"Oi Ting Cheung (Joey)", :gender=>"female ", :email=>"otchung@ucdavis.edu", :phone_number=>"5304008742", :user_id=>14, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Alora", :gender=>"female ", :email=>"thktsang@ucdavis.edu", :phone_number=>"2065780625", :user_id=>22, :school_status=>"undergrad", :major=>"Applied Math", :admin_level=>mack})
Contact.create({:name=>"Hao Zeng (Hughe)", :gender=>"male", :email=>"haozeng@ucdavis.edu", :phone_number=>"5303027318", :user_id=>16, :school_status=>"visiting scholar ", :major=>"cloth and textile", :admin_level=>mack})
Contact.create({:name=>"Ruiqi Shao ", :gender=>"male", :email=>"shaoruiqi1225@gmail.com", :phone_number=>"5302207123", :user_id=>22, :school_status=>"visiting scholar ", :major=>"cloth and textile", :admin_level=>mack})
Contact.create({:name=>"Yanling Zeng", :gender=>"female ", :email=>"ylzeng@ucdavis.edu", :phone_number=>"5305309721", :user_id=>14, :school_status=>"undergrad", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Lily", :gender=>"female", :email=>"Wxuli@ucdavis.edu", :phone_number=>"5302202695", :user_id=>14, :school_status=>"Undergraduate Student", :major=>"Psychology", :admin_level=>mack})
Contact.create({:name=>"Chen Wang ", :gender=>"female", :email=>"ocenwangchen@gmail.com", :phone_number=>nil, :user_id=>13, :school_status=>"Other", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Ayaka Uchida", :gender=>"female", :email=>"auchida@ucdavis.edu", :phone_number=>"81-80-4034-6021", :user_id=>2, :school_status=>"Exchange Student", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Lauren Barr", :gender=>"female", :email=>"labarr@ucdavis.edu", :phone_number=>"785-806-1148", :user_id=>2, :school_status=>"Undergraduate", :major=>"Japanese & IR", :admin_level=>mack})
Contact.create({:name=>"misaki ide", :gender=>"female", :email=>"mide@ucdavis.edu", :phone_number=>nil, :user_id=>2, :school_status=>"Exchange Student", :major=>"Politics ", :admin_level=>mack})
Contact.create({:name=>"Jing Jiang", :gender=>"female", :email=>"jinjiang@ucdavis.edu", :phone_number=>nil, :user_id=>5, :school_status=>"Post grad, working in Lab", :major=>"Food Science ", :admin_level=>mack})
Contact.create({:name=>"Miu Ueda", :gender=>"female", :email=>"mueda@ucdavis.edu", :phone_number=>nil, :user_id=>2, :school_status=>"Exchange Student", :major=>"Literature ", :admin_level=>mack})
Contact.create({:name=>"Niki", :gender=>"female", :email=>"Qmguo@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"Undergraduate Student", :major=>"Nutrition ", :admin_level=>mack})
Contact.create({:name=>"Hiroto", :gender=>"male", :email=>"hkonishi@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"Undergraduate Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"ryota tajima ", :gender=>"male", :email=>"ryota1103171@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>"Undergraduate Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"Mino", :gender=>"male", :email=>"sminoya@ucdavis.edu", :phone_number=>"08045031301", :user_id=>22, :school_status=>"Undergraduate Student", :major=>"Literature ", :admin_level=>mack})
Contact.create({:name=>"Ryotaro", :gender=>"male", :email=>"michael got contact info", :phone_number=>nil, :user_id=>22, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Akane ", :gender=>"female", :email=>"yamauntain10@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>"Exchange Student", :major=>"Management,", :admin_level=>mack})
Contact.create({:name=>"Chiyomi", :gender=>"female", :email=>"cnomura@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"Exchange Student", :major=>"Literature ", :admin_level=>mack})
Contact.create({:name=>"Ayana", :gender=>"female", :email=>"ayn.sj6823@icloud.com", :phone_number=>"09051368474", :user_id=>2, :school_status=>"Exchange Student", :major=>"social science", :admin_level=>mack})
Contact.create({:name=>"Moe Umeki", :gender=>"female", :email=>"mumeki@ucdavis.edu", :phone_number=>nil, :user_id=>2, :school_status=>"Exchange Student", :major=>"Economics", :admin_level=>mack})
Contact.create({:name=>"Maria Kurokawa", :gender=>"female", :email=>"mariahorse929@icloud.com", :phone_number=>nil, :user_id=>14, :school_status=>"Exchange Student", :major=>"Literature ", :admin_level=>mack})
Contact.create({:name=>"Taiki Nagai", :gender=>"male", :email=>"terikubu4275@icloud.com", :phone_number=>nil, :user_id=>22, :school_status=>"Exchange Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"Ai Sugiyama", :gender=>"female", :email=>"aisugiyama@ucdavis.edu", :phone_number=>"08061457601", :user_id=>14, :school_status=>"Undergraduate Student", :major=>"social science", :admin_level=>mack})
Contact.create({:name=>"Jiapeng", :gender=>"male", :email=>"601799422@qq.com", :phone_number=>nil, :user_id=>22, :school_status=>"Graduate Student", :major=>"Tourism management", :admin_level=>mack})
Contact.create({:name=>"Lei", :gender=>"female", :email=>"leiqian@ucdavis.com", :phone_number=>"6262721881", :user_id=>5, :school_status=>"Graduate Student", :major=>"sociology ", :admin_level=>mack})
Contact.create({:name=>"Hossein", :gender=>"male", :email=>"H.mehrabinejad@ucdavis.edr", :phone_number=>"5307608940", :user_id=>22, :school_status=>"Visiting Scholar", :major=>"Chemistry", :admin_level=>mack})
Contact.create({:name=>"David", :gender=>"male", :email=>"  - Jing (wife is on newsletter)", :phone_number=>nil, :user_id=>22, :school_status=>"Visiting Scholar", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Esther  Zhang", :gender=>"female", :email=>"yuanzhangimh@gmail.com", :phone_number=>nil, :user_id=>14, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Wenyi Liang", :gender=>"female", :email=>"Wsliang@ucdavis.edu", :phone_number=>nil, :user_id=>14, :school_status=>"Undergraduate Student", :major=>"design", :admin_level=>mack})
Contact.create({:name=>"Francisco", :gender=>"male", :email=>"francisco.aj91@gmail.com", :phone_number=>nil, :user_id=>22, :school_status=>"Exchange Student", :major=>"veterinary medicine", :admin_level=>mack})
Contact.create({:name=>"Shino ", :gender=>"female", :email=>" - returned", :phone_number=>nil, :user_id=>15, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Marina ", :gender=>"female", :email=>" - returned", :phone_number=>nil, :user_id=>2, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Noriko", :gender=>"female", :email=>" - returned", :phone_number=>nil, :user_id=>15, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Eddie", :gender=>"male", :email=>"cczhou@ucdavis.edu", :phone_number=>"5307613414", :user_id=>17, :school_status=>"Graduate", :major=>"Computer Science", :admin_level=>mack})
Contact.create({:name=>"Emma", :gender=>"female", :email=>"eslangguth@ucdavis.edu", :phone_number=>"5302048758", :user_id=>3, :school_status=>"Visiting Scholar", :major=>"CCM", :admin_level=>mack})
Contact.create({:name=>"Sophia Mundigl", :gender=>"female", :email=>"sophia.mundigl@web.de", :phone_number=>"530 979 3235", :user_id=>3, :school_status=>"Visiting Scholar", :major=>"CCM", :admin_level=>mack})
Contact.create({:name=>"Wenbo", :gender=>"male", :email=>"wgeng@ucdavis.edu", :phone_number=>nil, :user_id=>22, :school_status=>"Undergraduate", :major=>"Econ", :admin_level=>mack})

Contact.create({:name=>"Britney Lin", :gender=>"female", :email=>"1793066617@qq.com", :phone_number=>nil, :user_id=>2, :school_status=>"Undergraduate Student", :major=>"Math", :admin_level=>mack})
Contact.create({:name=>"Eunkyung", :gender=>"female", :email=>"eklove86@gmail.com", :phone_number=>"7078803323", :user_id=>13, :school_status=>"the wife of Phd student", :major=>"no", :admin_level=>mack})
Contact.create({:name=>"James Wang", :gender=>"male", :email=>"haohsuanw@gmail.com", :phone_number=>"6503051186", :user_id=>22, :school_status=>"Exchange Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"Jasmine", :gender=>"female", :email=>"Qijlai@ucdavis.edu", :phone_number=>"6262978489", :user_id=>3, :school_status=>"Undergraduate Student", :major=>"Economics", :admin_level=>mack})
Contact.create({:name=>"Jolie", :gender=>"female", :email=>"joliejxm@gmail.com", :phone_number=>"5304009804", :user_id=>13, :school_status=>"housewife", :major=>"chemistry", :admin_level=>mack})
Contact.create({:name=>"Kareem Khan Mohammed ", :gender=>"male", :email=>"mokkhan@ucdavis.edu", :phone_number=>"5305376507", :user_id=>22, :school_status=>"Graduate Student", :major=>"Electrical and Computer Engineering", :admin_level=>mack})
Contact.create({:name=>"Kunjie Pang", :gender=>"male", :email=>"pkmartin123@gmail.com", :phone_number=>"2067347173", :user_id=>17, :school_status=>"Graduate Student", :major=>"forensic science", :admin_level=>mack})
Contact.create({:name=>"Maryam Sahranavard", :gender=>"female", :email=>"msahranavard@ucdavis.edu", :phone_number=>"5307608562", :user_id=>22, :school_status=>"Visiting Scholar", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Mudi", :gender=>"male", :email=>"opojeme@ucdavis.edu", :phone_number=>"5303838773", :user_id=>22, :school_status=>"Graduate Student", :major=>"law", :admin_level=>mack})
Contact.create({:name=>"Silvia Noble", :gender=>"female", :email=>"snoble@ucdavis.edu", :phone_number=>"530-979-3074", :user_id=>20, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Val", :gender=>"male", :email=>"valyqh@gmail.com", :phone_number=>"5302199879", :user_id=>22, :school_status=>"Graduate Student", :major=>"chemistry", :admin_level=>mack})
Contact.create({:name=>"Yu Hin Chan (Addie)", :gender=>"male", :email=>"yuhchan@ucdavis.edu", :phone_number=>"5309793122", :user_id=>17, :school_status=>"Graduate Student", :major=>"Mathematics", :admin_level=>mack})
Contact.create({:name=>"James", :gender=>"male", :email=>nil, :phone_number=>nil, :user_id=>17, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Chihiro Suzuki", :gender=>"female", :email=>"luck4510471@yahoo.co.jp", :phone_number=>nil, :user_id=>17, :school_status=>"Exchange Student", :major=>nil, :admin_level=>mack})
Contact.create({:name=>"Mio Owa", :gender=>"female", :email=>"g.bigring1204@gmail.com", :phone_number=>"5307238096", :user_id=>2, :school_status=>"Exchange Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"Ami Tsujihara", :gender=>"female", :email=>"atsujihara@ucdavis.edu", :phone_number=>"5303641164", :user_id=>2, :school_status=>"Exchange Student", :major=>"English", :admin_level=>mack})
Contact.create({:name=>"Chen Li", :gender=>"female", :email=>"cnli@ucdavis.edu", :phone_number=>nil, :user_id=>8, :school_status=>"Visiting Scholar", :major=>"Food Science", :admin_level=>mack})
Contact.create({:name=>"Sakura Kinashita", :gender=>"female", :email=>"sakuran_ran@icloud.com", :phone_number=>"090-5645-3541", :user_id=>15, :school_status=>"Exchange Student", :major=>"International communications", :admin_level=>mack})
Contact.create({:name=>"Yuki Hikawa", :gender=>"female", :email=>"yhikawa@ucdavis.edu", :phone_number=>nil, :user_id=>3, :school_status=>"Exchange Student", :major=>"International communication ", :admin_level=>mack})
Contact.create({:name=>"yumena mori", :gender=>"female", :email=>"yummori@ucdavis.edu", :phone_number=>nil, :user_id=>14, :school_status=>"Exchange Student", :major=>"international communication", :admin_level=>mack})
Contact.create({:name=>"Mako Kitagawa", :gender=>"female", :email=>"t1111m0704.love@gmail.com", :phone_number=>"9018947850", :user_id=>20, :school_status=>"Undergraduate", :major=>"Literature", :admin_level=>mack})
Contact.create({:name=>"MAI UKAI", :gender=>"female", :email=>"umaimai.bmt.10@icloud.com", :phone_number=>"5307238104", :user_id=>21, :school_status=>"Exchange Student", :major=>"international communication", :admin_level=>mack})
Contact.create({:name=>"Eri", :gender=>"female", :email=>"mzerisd@outlook.jp", :phone_number=>nil, :user_id=>15, :school_status=>"Visiting Scholar", :major=>"International", :admin_level=>mack})
Contact.create({:name=>"Sakura Kinashita", :gender=>"female", :email=>"sakuran_ran@icloud.com", :phone_number=>"090-5645-3541", :user_id=>15, :school_status=>"Exchange Student", :major=>"International communications", :admin_level=>mack})
Contact.create({:name=>"Jinyoung", :gender=>"male", :email=>"jyseo0226@gmail.com", :phone_number=>"7078139057", :user_id=>22, :school_status=>"Graduate Student", :major=>"Economics", :admin_level=>mack})
Contact.create({:name=>"Tomohiro", :gender=>"male", :email=>"tyamagata@ucdavis.edu", :phone_number=>"09091666037", :user_id=>22, :school_status=>"Law", :major=>"Exchange", :admin_level=>mack})
Contact.create({:name=>"Shu Ning (Ashley)", :gender=>"female", :email=>"XSHNING@UCDAVIS.EDU", :phone_number=>nil, :user_id=>19, :school_status=>nil, :major=>nil, :admin_level=>mack})
Contact.create({:name=>"ikumi ikeda", :gender=>"female", :email=>"iikeda@ucdavis.edu", :phone_number=>nil, :user_id=>2, :school_status=>"Exchange Student", :major=>"east asia", :admin_level=>mack})
Contact.create({:gender=>"male", :name=>"Tyler Jan", :user_id=>17, :school_status=>"Masters", :email=>"wjan@ucdavis.edu", :phone_number=>"312-404-4100", :major=>"computer science", :admin_level=>mack})
Contact.create({:gender=>"female", :name=>"Amanda Lin", :user_id=>22, :school_status=>"did not indicate", :email=>"alin0918@gmail.com (double check paper)", :phone_number=>"217-503-7498", :major=>nil, :admin_level=>mack})
Contact.create({:gender=>"female", :name=>"Lei He", :user_id=>13, :school_status=>"Other", :email=>"cowhelei1887@gmail.com", :phone_number=>"N/A", :major=>"N/A", :admin_level=>mack})
Contact.create({:gender=>"male", :name=>"Shan", :user_id=>22, :school_status=>"Masters", :email=>"shjiang@ucdavis.edu", :phone_number=>"530-601-3461", :major=>"statistics", :admin_level=>mack})
Contact.create({:gender=>"female", :name=>"Shuang", :user_id=>13, :school_status=>"Visiting Scholar (PhD)", :email=>nil, :phone_number=>nil, :major=>"Chemical Engineering", :admin_level=>mack})
puts "done!"
